services:
        site:
                image: gabicunha7/autobotics-site:1.5
                ports:
                        - "3333:3333"
                networks:
                        - rede-pizza
                depends_on:
                        - db
        db:
                image: gabicunha7/autobotics-bd:1.1
                ports:
                        - "3306:3306"
                networks:
                        - rede-pizza
networks:
        rede-pizza:
                driver: bridge
